/**
 * Database type definitions for Supabase.
 *
 * This file will be auto-generated by the Supabase CLI once migrations
 * are applied:
 *   npx supabase gen types typescript --local > types/database.ts
 *
 * For Sprint 1, we define the structural shape. Types will be expanded
 * in Sprint 2 when database migrations are applied.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          created_at: string
          onboarding_status: 'incomplete' | 'completed'
        }
        Insert: {
          id: string
          email: string
          created_at?: string
          onboarding_status?: 'incomplete' | 'completed'
        }
        Update: {
          id?: string
          email?: string
          created_at?: string
          onboarding_status?: 'incomplete' | 'completed'
        }
      }
      profiles: {
        Row: {
          id: string
          full_name: string
          date_of_birth: string
          biological_sex: 'male' | 'female'
          height: number
          current_weight: number
          target_weight: number
          fitness_level: 'beginner' | 'intermediate' | 'advanced'
          equipment_access: string
          injuries_list: string[]
          dietary_restrictions: string[]
          updated_at: string
        }
        Insert: {
          id: string
          full_name: string
          date_of_birth: string
          biological_sex: 'male' | 'female'
          height: number
          current_weight: number
          target_weight: number
          fitness_level: 'beginner' | 'intermediate' | 'advanced'
          equipment_access: string
          injuries_list?: string[]
          dietary_restrictions?: string[]
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string
          date_of_birth?: string
          biological_sex?: 'male' | 'female'
          height?: number
          current_weight?: number
          target_weight?: number
          fitness_level?: 'beginner' | 'intermediate' | 'advanced'
          equipment_access?: string
          injuries_list?: string[]
          dietary_restrictions?: string[]
          updated_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      onboarding_status: 'incomplete' | 'completed'
      biological_sex: 'male' | 'female'
      fitness_level: 'beginner' | 'intermediate' | 'advanced'
      primary_goal: 'fat_loss' | 'muscle_gain' | 'recomposition' | 'general_fitness'
    }
    CompositeTypes: Record<string, never>
  }
}

// ─── Convenience type aliases ────────────────────────────────────────────────
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']

export type Enums<T extends keyof Database['public']['Enums']> =
  Database['public']['Enums'][T]
